@startuml
class App{
start()
main()
}

class WindowController{
-DialogManager
-FileManager
-Inventory

}

class DialogManager{

}

class FileManager{
+saveInventory()
+loadInventory()

}

class Inventory{
- catalog: observableList<Item>
- InputValidator

+addItem()
+removeItem()
+editItem()
+sortItems()
+searchSerial()
+searchName()
+getCatalog()
}

class Item{
-name: String
-serialNumber: String
-value: BigDecimal

+getName()
+getSerialNumber()
+getValue()

}

class InputValidator{
+ formatDollars()
+ uniqueSerial()
+ formatSerial()
+ nameLength()
}

openfx.org.Application <|-- App
App -- WindowController
WindowController o-- DialogManager
WindowController o-- FileManager
WindowController o-- Inventory
Inventory *-- Item
Inventory *-- InputValidator
@enduml