@startuml
class App{
start()
main()
}

class WindowController{
- dm: DialogManager
- fm: FileManager
- userInventory: Inventory
- catalog: ObservableList<Item>

+updateTableView()
}

class DialogManager{
}

class FileManager{
+saveInventory()
+loadInventory()
}

class Inventory{
- catalog: ArrayList<Item>

+addItem()
+removeItem()
+editItem()
+sortItems()
+searchSerial()
+searchName()
+getCatalog()
}

class Item{
-name: String
-serialNumber: String
-value: BigDecimal

+setName(String)
+setSerialNumber(String)
+setValue(BigDecimal)
+getName()
+getSerialNumber()
+getValue()
}

class InputValidator{
+ checkValue()
+ checkUniqueSerial()
+ checkFormatSerial()
+ checkNameLength()
}

openfx.org.Application <|-- App
App -- WindowController
WindowController o-- DialogManager
WindowController o-- FileManager
WindowController o-- Inventory
Inventory *-- Item
WindowController o-- InputValidator
@enduml