@startuml
class App{
start()
main()
}

class WindowController{
- userInventory: Inventory
- iv: InputValidator
- dm: DialogManager
- fm: FileManager

- catalog: ObservableList<Item>

+initialize()
+updateTableView()
+bAddItem()
+bDeleteItem()
+bEdit()
}

class DialogManager{
+reportErrorItem()
+reportError()
+getEditItemDialog()
}

class FileManager{
+saveInventory()
+loadInventory()
}

class Inventory{
- catalog: ArrayList<Item>

+addItem()
+removeItem()
+editItem()
+sortItems()
+searchSerial()
+searchName()
+getCatalog()
}

class Item{
-name: String
-serialNumber: String
-value: BigDecimal

+setName()
+setSerialNumber()
+setValue()
+getName()
+getSerialNumber()
+getValue()
}

class InputValidator{
+ checkValue()
+ checkUniqueSerial()
+ checkFormatSerial()
+ checkNameLength()
}

openfx.org.Application <|-- App
App -- WindowController
WindowController o-- DialogManager
WindowController o-- FileManager
WindowController o-- Inventory
Inventory *-- Item
WindowController o-- InputValidator
@enduml